name: dart_graph
description: "A geomtry util library"
version: 1.0.6

homepage: https://github.com/Go-oG/d_graph


environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.2.2
  collection: ^1.19.1
  uuid: ^4.5.1
  d_util: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
